Repository AY2122S2-CS2103T-W11-2/tp, pull requests merged in 2022-03, with the labels that each got.

#16 Update DG: Non-Functional Requirements, Glossary
  docs/DeveloperGuide.md
Labels: documentation

#19 Add personal details
  docs/AboutUs.md
  docs/images/eman-kom.png
  docs/team/eman-kom.md
Labels: documentation

#24 remove portfolio line from about us
  docs/AboutUs.md
Labels: documentation

#41 Branch change delete
  .gitignore
  .vscode/settings.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/imrajsinghsandhu.md
  docs/team/rcjj98.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#44 Add find by job id functionality
  docs/UserGuide.md
  dummytext.txt
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation, type.Task

#45 Overhaul find command
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
Labels: documentation, type.Story, type.Enhancement

#55 Update DG for new delete command functionality
  .gitignore
  .vscode/settings.json
  docs/DeveloperGuide.md
Labels: documentation

#54 Branch v1.2 editcommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/Job.java
  src/main/java/seedu/address/model/application/Stage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation, type.Story
